### ISSUE TITLE
Останавливается контейнер

### ISSUE THREAD

**Issue by ms4b** [alexanderfefelov/docker-1c-server#5]
Собрал по инструкции с платформой 8.3.13-1513.
Контейнер успешно стартует и сразу останавливается.

**Comment by alexanderfefelov** [comment]
Что говорит docker logs?

**Comment by alexanderfefelov** [comment]
Какие-нибудь подробности будут?

**Comment by alexanderfefelov** [comment]
Топик-стартер не отвечает.
