### ISSUE TITLE
Ошибка запуска контейнера

### ISSUE THREAD

**Issue by sealab2066** [alexanderfefelov/docker-1c-server#6]
Делаю все по инструкции, в итоге после запуска sudo ./run.sh выдает

Unable to find image 'alexanderfefelov/1c-server:latest' locally
docker: Error response from daemon: pull access denied for alexanderfefelov/1c-server, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by alexanderfefelov** [comment]
Чем закончился запуск `build.sh`? Что выдаёт `docker image ls`?

**Comment by sealab2066** [comment]
![docker1c](https://user-images.githubusercontent.com/17637953/56362496-af261800-61f2-11e9-8073-355e2432e3b0.png)

Стоит docker ce 
Docker version 18.09.5, build e8ff056

**Comment by alexanderfefelov** [comment]
`build.sh` отработал с ошибкой. Образ не был создан.

**Comment by alexanderfefelov** [comment]
Подозреваю, что не было сделано или было сделано неправильно вот это:

> Скопируйте deb-файлы дистрибутива сервера 1С:Предприятия в каталог docker-1c-server и затем.

**Comment by sealab2066** [comment]
Скачал самый свежий билд (вчерашний)
![2](https://user-images.githubusercontent.com/17637953/56363864-d5998280-61f5-11e9-8af3-c62cc7e3a1ab.png)
Он же копирует их в папку tmp и оттуда ставит? Может в tmp на моей машине копирование не происходит?

**Comment by alexanderfefelov** [comment]
В `Dockerfile` есть привязка к версии 1С, см. [здесь](https://github.com/alexanderfefelov/docker-1c-server/blob/master/Dockerfile#L26). Нужно отредактировать `Dockerfile`.

**Comment by sealab2066** [comment]
Да, помогло. Указал версию. Вы может быть допишете это в мануал? что-то вроде "Версия 1с захардкожена в Dockerfile, впишите свою если отличается"

**Comment by alexanderfefelov** [comment]
> Вы может быть допишете это в мануал.

Выдастся свободное время - сделаю.

**Comment by hardlemondrink** [comment]
под centos не прокатит обыкновенное изменение расширений с deb на rpm? пробую и билд с возвратом 8 завершается

**Comment by alexanderfefelov** [comment]
> изменение расширений с deb на rpm

Не прокатит. Но, вроде, существуют конвертеры туда-сюда.
